name: Unit Tests
on: [push, pull_request]

env:
  VSTEST_CONNECTION_TIMEOUT: 180

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        framework: ["net452", "netcoreapp3.1"]
        suite: ["unittest", "dotNetRDF.MockServerTests"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Tests
      run: dotnet test -c Release --filter "Category!=explicit" --framework ${{ matrix.framework }} Testing\${{matrix.suite}}
    
